---
apiVersion: v1
kind: Pod
metadata:
  name: resource-test
spec:
  containers:
  - name: resource-test
    image: harbor.opscoffee.com/test/nginx_test:v1
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
